CREATE TABLE IF NOT EXISTS invite_links (
  id SERIAL PRIMARY KEY,
  match_id INTEGER NOT NULL,
  code VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP NOT NULL,
  FOREIGN KEY (match_id) REFERENCES match(id) ON DELETE CASCADE
);
