name: Build Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (webapp)
        uses: docker/build-push-action@v5
        with:
          context: ./webapp
          file: ./webapp/Dockerfile
          push: false
          tags: webapp:latest

      - name: Install dependencies and run tests
        run: |
          cd webapp
          npm ci
          npm run test

      # Optional: Add steps to push to registry or run tests
      # - name: Log in to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Push image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./webapp
      #     file: ./webapp/Dockerfile
      #     push: true
      #     tags: yourdockerhubuser/webapp:latest
